{% set name = "rdflib" %}
{% set version = "6.0.1" %}
{% set sha256 = "c7404d56bed449ff4802ed54f0b864b552075a4f9d1f9bf6ef7e27b51d4656a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rdflib/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py < 37]
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - isodate
    - pyparsing
    - html5lib
    - requests
    - sparqlwrapper

test:
  imports:
    - rdflib
    - rdflib.extras
    - rdflib.plugins
    - rdflib.plugins.parsers
    - rdflib.plugins.parsers
    - rdflib.plugins.serializers
    - rdflib.plugins.sparql
    - rdflib.plugins.stores
    - rdflib.tools

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD-3-Clause
  license_file: LICENSE
  summary: RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
  dev_url: https://github.com/RDFLib/rdflib
  doc_url: https://rdflib.readthedocs.io

extra:
  recipe-maintainers:
    - satra
    - nicholascar
