{% set name = "rdflib" %}
{% set version = "4.2.2" %}
{% set sha256 = "da1df14552555c5c7715d8ce71c08f404c988c58a1ecd38552d0da4fc261280d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - rdfpipe = rdflib.tools.rdfpipe:main
    - csv2rdf = rdflib.tools.csv2rdf:main
    - rdf2dot = rdflib.tools.rdf2dot:main
    - rdfs2dot = rdflib.tools.rdfs2dot:main
    - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - isodate
    - pyparsing

  run:
    - python
    - isodate
    - pyparsing
    - html5lib
    - sparqlwrapper

test:
  imports:
    - rdflib
    - rdflib.extras
    - rdflib.plugins
    - rdflib.plugins.parsers
    - rdflib.plugins.parsers.pyMicrodata
    - rdflib.plugins.parsers.pyRdfa
    - rdflib.plugins.parsers.pyRdfa.extras
    - rdflib.plugins.parsers.pyRdfa.host
    - rdflib.plugins.parsers.pyRdfa.rdfs
    - rdflib.plugins.parsers.pyRdfa.transform
    - rdflib.plugins.serializers
    - rdflib.plugins.sparql
    - rdflib.plugins.sparql.results
    - rdflib.plugins.stores
    - rdflib.tools

  commands:
    - rdfpipe --help
    - rdfgraphisomorphism --help

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.'
  dev_url: https://github.com/RDFLib/rdflib
  doc_url: https://rdflib.readthedocs.io

extra:
  recipe-maintainers:
    - satra
