# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 7.1.4
  python_test_max: "3.13"

recipe:
  name: rdflib
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/rdflib/rdflib-${{ version }}.tar.gz
    sha256: fed46e24f26a788e2ab8e445f7077f00edcf95abb73bcef4b86cefa8b62dd174
    target_directory: dist
  - url: https://github.com/RDFLib/rdflib/archive/refs/tags/${{ version }}.tar.gz
    sha256: b70da12023f6667464d68009e429a5fceeb8d83a891863ce85c6df0615b7e4ab
    target_directory: src

build:
  number: 0

outputs:
  - package:
      name: rdflib
    build:
      number: 0
      noarch: python
      script:
        - cd dist
        - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - csv2rdf = rdflib.tools.csv2rdf:main
          - rdf2dot = rdflib.tools.rdf2dot:main
          - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main
          - rdfpipe = rdflib.tools.rdfpipe:main
          - rdfs2dot = rdflib.tools.rdfs2dot:main
    requirements:
      host:
        - pip
        - poetry-core >=2.0.0
        - python ${{ python_min }}.*
      run:
        - isodate >=0.7.0,<1.0.0
        - pyparsing >=3.2.0,<4
        - python >=${{ python_min }}
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}
        script:
          - which csv2rdf              || where csv2rdf              || exit 1
          - which rdf2dot              || where rdf2dot              || exit 1
          - which rdfgraphisomorphism  || where rdfgraphisomorphism  || exit 1
          - which rdfpipe              || where rdfpipe              || exit 1
          - which rdfs2dot             || where rdfs2dot             || exit 1

  - package:
      name: rdflib-with-networkx
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib", upper_bound="x.x.x") }}
        - networkx >=2,<4
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - python -c "from rdflib.extras.external_graph_libs import rdflib_to_networkx_graph; import rdflib; assert rdflib_to_networkx_graph(rdflib.Graph()) is not None"

  - package:
      name: rdflib-with-html
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib", upper_bound="x.x.x") }}
        - html5rdf >=1.2.1,<2
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - python -c "from rdflib import term; assert term.html5rdf"

  - package:
      name: rdflib-with-lxml
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib", upper_bound="x.x.x") }}
        - lxml >=4.9.3,<6.0
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - python -c "from rdflib.plugins.sparql.results import xmlresults; assert xmlresults.lxml_etree"

  - package:
      name: rdflib-with-orjson
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib", upper_bound="x.x.x") }}
        - orjson >=3.9.14,<4
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}
        script:
          - python -c "from rdflib.plugins.sparql.results import jsonresults; assert jsonresults.orjson"

  - package:
      name: rdflib-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib-with-html", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("rdflib-with-lxml", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("rdflib-with-networkx", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("rdflib-with-orjson", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("rdflib", upper_bound="x.x.x") }}
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*

  - package:
      name: _rdflib-tests
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("rdflib-with-all", upper_bound="x.x.x") }}
    tests:
      - python:
          imports: rdflib
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_test_max }}.*
      - files:
          recipe:
            - run_rdflib_suite.py
          source:
            - src/examples/
            - src/pyproject.toml
            - src/test/
        requirements:
          run:
            - python ${{ python_min }}
            - pytest-cov
            - setuptools
        script:
          - python run_rdflib_suite.py

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE
  summary: RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
  homepage: https://github.com/RDFLib/rdflib
  repository: https://github.com/RDFLib/rdflib
  documentation: https://rdflib.readthedocs.io

extra:
  feedstock-name: rdflib
  recipe-maintainers:
    - aucampia
    - satra
    - nicholascar
    - bollwyvl
